# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: foil
  theme_night: 
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: EducationalOrganization
    org_name: 'Functional Optical Imaging Laboratory'
    description: 'The Functional Optical Imaging Laboratory (FOIL) is dedicated to developing novel optical imaging technologies for studying the brain.'
    twitter: ''
  analytics:
    google_analytics: 'G-E0Y2HE9YLG'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: |
      © {year} Functional Optical Imaging Laboratory<br/>
      Powered by [Hugo](https://gohugo.io/) and [Wowchemy](https://wowchemy.com/)
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - latex
      - r
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/utfoil/foil.bme.utexas.edu'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    wowchemy:
      min_length: 3  # Only the matches whose length exceeds this value will be returned.
      threshold: 0.25  # Where 0 requires a perfect match and 1 matches anything.
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 17

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Publication style

publications:
  date_format: January 2006
  citation_style: mla

# Project style

projects:
  publication_view: citation

# Sponsorship

i_am_a_sponsor: true
power_ups:
  hide_published_with: true
